services:
  mysql:
    image: mysql:9.7.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p\"$${MYSQL_ROOT_PASSWORD}\""]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - mysql-data:/var/lib/mysql
  
  app:
    image: cr.yandex/crpm5u802b9d7cp3853s/gradle-app:latest
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql-data:
    driver: local
