apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- range .Values.externalEnvVars }}
          - name: {{ .name }}
            valueFrom:
              {{- if eq .type "secret" }}
              secretKeyRef:
                name: {{ $.Values.secretName }}
                key: {{ .key }}
              {{- else if eq .type "configmap" }}
              configMapKeyRef:
                name: {{ $.Values.configMapName }}
                key: {{ .key }}
              {{- end }}
        {{- end }}