apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}
          failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          periodSeconds: {{ .Values.probes.startup.periodSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
        env:
        {{- range .Values.externalEnvVars }}
          - name: {{ .name }}
            valueFrom:
              {{- if eq .type "secret" }}
              secretKeyRef:
                name: {{ $.Values.secretName }}
                key: {{ .key }}
              {{- else if eq .type "configmap" }}
              configMapKeyRef:
                name: {{ $.Values.configMapName }}
                key: {{ .key }}
              {{- end }}
        {{- end }}
